[versions]
androidx-core = "1.12.0"
androidx-lifecycle = "2.7.0"
androidx-activity-compose = "1.8.2"
androidx-compose-bom = "2023.10.01"
androidx-compose-ui = "1.5.4"
androidx-compose-material3 = "1.1.2"
androidx-navigation-compose = "2.7.5"
androidx-lifecycle-viewmodel-compose = "2.7.0"
androidx-texttospeech = "1.0.1"
androidx-media = "1.6.0"
junit = "4.13.2"
androidx-junit = "1.1.5"
androidx-espresso-core = "3.5.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation-compose" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle-viewmodel-compose" }
androidx-texttospeech = { module = "androidx.texttospeech:texttospeech", version.ref = "androidx-texttospeech" }
androidx-media = { module = "androidx.media:media", version.ref = "androidx-media" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso-core" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

[plugins]
android-application = { id = "com.android.application", version = "8.2.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.20" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version = "1.9.20" }